#include "BuildPKBUtils.h"

#include "../../spa/src/source_processor/token/TokenList.h"

using namespace source_processor;

using namespace std;

PKB BuildPKBSampleProgram() {
  PKB sample_pkb = PKB();

  Token plus("+", TokenType::ExpressionOp);
  Token div("/", TokenType::ExpressionOp);
  Token mult("*", TokenType::ExpressionOp);
  Token count("count", TokenType::VariableName);
  Token cenX("cenX", TokenType::VariableName);
  Token cenY("cenY", TokenType::VariableName);
  Token x("x", TokenType::VariableName);
  Token y("y", TokenType::VariableName);
  Token one("1", TokenType::ConstantValue);
  Token zero("0", TokenType::ConstantValue);

  TokenList tokens1;
  TokenList tokens10;
  TokenList tokens11;
  TokenList tokens12;
  TokenList tokens15;
  TokenList tokens16;
  TokenList tokens17;
  TokenList tokens20;
  TokenList tokens21;
  TokenList tokens22;
  TokenList tokens23;

  tokens1.Push(zero);
  tokens10.Push(zero);
  tokens11.Push(zero);
  tokens12.Push(zero);
  tokens15.Push(count).Push(plus).Push(one);
  tokens16.Push(cenX).Push(plus).Push(x);
  tokens17.Push(cenY).Push(plus).Push(y);
  tokens20.Push(one);
  tokens21.Push(cenX).Push(div).Push(count);
  tokens22.Push(cenY).Push(div).Push(count);
  tokens23.Push(cenX).Push(mult).Push(cenX).Push(plus).Push(cenY).Push(mult).Push(cenY);

  for (int i = 1; i <= 23; i++) {
    sample_pkb.InsertStatement(i);
  }
  sample_pkb.InsertProcedure("main", 1, 3);
  sample_pkb.InsertProcedure("readPoint", 4, 5);
  sample_pkb.InsertProcedure("printResults", 6, 9);
  sample_pkb.InsertProcedure("computeCentroid", 10, 23);
  sample_pkb.InsertVariable("flag");
  sample_pkb.InsertVariable("x");
  sample_pkb.InsertVariable("y");
  sample_pkb.InsertVariable("flag");
  sample_pkb.InsertVariable("cenX");
  sample_pkb.InsertVariable("cenY");
  sample_pkb.InsertVariable("normSq");
  sample_pkb.InsertVariable("count");
  sample_pkb.InsertVariable("cenX");
  sample_pkb.InsertVariable("cenY");
  sample_pkb.InsertVariable("x");
  sample_pkb.InsertVariable("y");
  sample_pkb.InsertVariable("count");
  sample_pkb.InsertVariable("cenX");
  sample_pkb.InsertVariable("x");
  sample_pkb.InsertVariable("cenY");
  sample_pkb.InsertVariable("y");
  sample_pkb.InsertVariable("count");
  sample_pkb.InsertVariable("flag");
  sample_pkb.InsertVariable("cenX");
  sample_pkb.InsertVariable("count");
  sample_pkb.InsertVariable("cenY");
  sample_pkb.InsertVariable("count");
  sample_pkb.InsertVariable("normSq");
  sample_pkb.InsertVariable("cenX");
  sample_pkb.InsertVariable("cenY");
  sample_pkb.InsertAssignment(1, {"flag"}, tokens1);
  sample_pkb.InsertAssignment(10, {"count"}, tokens10);
  sample_pkb.InsertAssignment(11, {"cenX"}, tokens11);
  sample_pkb.InsertAssignment(12, {"cenY"}, tokens12);
  sample_pkb.InsertAssignment(15, {"count"}, tokens15);
  sample_pkb.InsertAssignment(16, {"cenX"}, tokens16);
  sample_pkb.InsertAssignment(17, {"cenY"}, tokens17);
  sample_pkb.InsertAssignment(20, {"flag"}, tokens20);
  sample_pkb.InsertAssignment(21, {"cenX"}, tokens21);
  sample_pkb.InsertAssignment(22, {"cenY"}, tokens22);
  sample_pkb.InsertAssignment(23, {"normSq"}, tokens23);
  sample_pkb.InsertConstant(0);
  sample_pkb.InsertConstant(0);
  sample_pkb.InsertConstant(0);
  sample_pkb.InsertConstant(0);
  sample_pkb.InsertConstant(0);
  sample_pkb.InsertConstant(0);
  sample_pkb.InsertConstant(1);
  sample_pkb.InsertConstant(1);
  sample_pkb.InsertCalls(2, "computeCentroid");
  sample_pkb.InsertCalls(3, "printResults");
  sample_pkb.InsertCalls(13, "readPoint");
  sample_pkb.InsertCalls(18, "readPoint");
  sample_pkb.InsertRead(4, "x");
  sample_pkb.InsertRead(5, "y");
  sample_pkb.InsertPrint(6, "flag");
  sample_pkb.InsertPrint(7, "cenX");
  sample_pkb.InsertPrint(8, "cenY");
  sample_pkb.InsertPrint(9, "normSq");
  sample_pkb.InsertWhile(14, {"x", "y"});
  sample_pkb.InsertIf(19, {"count"});
  sample_pkb.InsertFollows(1, 2);
  sample_pkb.InsertFollowsT(1, 2);
  sample_pkb.InsertFollows(2, 3);
  sample_pkb.InsertFollowsT(2, 3);
  sample_pkb.InsertFollowsT(1, 3);
  sample_pkb.InsertFollows(4, 5);
  sample_pkb.InsertFollowsT(4, 5);
  sample_pkb.InsertFollows(6, 7);
  sample_pkb.InsertFollowsT(6, 7);
  sample_pkb.InsertFollows(7, 8);
  sample_pkb.InsertFollowsT(7, 8);
  sample_pkb.InsertFollowsT(6, 8);
  sample_pkb.InsertFollows(8, 9);
  sample_pkb.InsertFollowsT(8, 9);
  sample_pkb.InsertFollowsT(6, 9);
  sample_pkb.InsertFollowsT(7, 9);
  sample_pkb.InsertFollows(10, 11);
  sample_pkb.InsertFollowsT(10, 11);
  sample_pkb.InsertFollows(11, 12);
  sample_pkb.InsertFollowsT(11, 12);
  sample_pkb.InsertFollowsT(10, 12);
  sample_pkb.InsertFollows(12, 13);
  sample_pkb.InsertFollowsT(12, 13);
  sample_pkb.InsertFollowsT(11, 13);
  sample_pkb.InsertFollowsT(10, 13);
  sample_pkb.InsertFollows(13, 14);
  sample_pkb.InsertFollowsT(13, 14);
  sample_pkb.InsertFollowsT(12, 14);
  sample_pkb.InsertFollowsT(11, 14);
  sample_pkb.InsertFollowsT(10, 14);
  sample_pkb.InsertFollows(14, 19);
  sample_pkb.InsertFollowsT(14, 19);
  sample_pkb.InsertFollowsT(13, 19);
  sample_pkb.InsertFollowsT(12, 19);
  sample_pkb.InsertFollowsT(11, 19);
  sample_pkb.InsertFollowsT(10, 19);
  sample_pkb.InsertFollows(19, 23);
  sample_pkb.InsertFollowsT(19, 23);
  sample_pkb.InsertFollowsT(14, 23);
  sample_pkb.InsertFollowsT(13, 23);
  sample_pkb.InsertFollowsT(12, 23);
  sample_pkb.InsertFollowsT(11, 23);
  sample_pkb.InsertFollowsT(10, 23);
  sample_pkb.InsertFollows(15, 16);
  sample_pkb.InsertFollowsT(15, 16);
  sample_pkb.InsertFollows(16, 17);
  sample_pkb.InsertFollowsT(16, 17);
  sample_pkb.InsertFollowsT(15, 17);
  sample_pkb.InsertFollows(17, 18);
  sample_pkb.InsertFollowsT(17, 18);
  sample_pkb.InsertFollowsT(16, 18);
  sample_pkb.InsertFollowsT(15, 18);
  sample_pkb.InsertFollows(21, 22);
  sample_pkb.InsertFollowsT(21, 22);

  sample_pkb.InsertParent(14, 15);
  sample_pkb.InsertParent(14, 16);
  sample_pkb.InsertParent(14, 17);
  sample_pkb.InsertParent(14, 18);
  sample_pkb.InsertParent(19, 20);
  sample_pkb.InsertParent(19, 21);
  sample_pkb.InsertParent(19, 22);
  sample_pkb.InsertParentT(14, 15);
  sample_pkb.InsertParentT(14, 16);
  sample_pkb.InsertParentT(14, 17);
  sample_pkb.InsertParentT(14, 18);
  sample_pkb.InsertParentT(19, 20);
  sample_pkb.InsertParentT(19, 21);
  sample_pkb.InsertParentT(19, 22);

  sample_pkb.InsertUses(2, "x");
  sample_pkb.InsertUses(2, "y");
  sample_pkb.InsertUses(2, "count");
  sample_pkb.InsertUses(2, "cenX");
  sample_pkb.InsertUses(2, "cenY");
  sample_pkb.InsertUses(2, "flag");
  sample_pkb.InsertUses(3, "flag");
  sample_pkb.InsertUses(3, "cenX");
  sample_pkb.InsertUses(3, "cenY");
  sample_pkb.InsertUses(3, "normSq");
  sample_pkb.InsertUses(6, "flag");
  sample_pkb.InsertUses(7, "cenX");
  sample_pkb.InsertUses(8, "cenY");
  sample_pkb.InsertUses(9, "normSq");
  sample_pkb.InsertUses(14, "x");
  sample_pkb.InsertUses(14, "y");
  sample_pkb.InsertUses(14, "count");
  sample_pkb.InsertUses(14, "cenX");
  sample_pkb.InsertUses(14, "cenY");
  sample_pkb.InsertUses(15, "count");
  sample_pkb.InsertUses(16, "cenX");
  sample_pkb.InsertUses(16, "x");
  sample_pkb.InsertUses(17, "cenY");
  sample_pkb.InsertUses(17, "y");
  sample_pkb.InsertUses(19, "count");
  sample_pkb.InsertUses(19, "cenX");
  sample_pkb.InsertUses(19, "cenY");
  sample_pkb.InsertUses(21, "count");
  sample_pkb.InsertUses(21, "cenX");
  sample_pkb.InsertUses(22, "count");
  sample_pkb.InsertUses(22, "cenY");
  sample_pkb.InsertUses(23, "cenX");
  sample_pkb.InsertUses(23, "cenY");

  sample_pkb.InsertUses("main", "flag");
  sample_pkb.InsertUses("main", "cenX");
  sample_pkb.InsertUses("main", "cenY");
  sample_pkb.InsertUses("main", "normSq");
  sample_pkb.InsertUses("main", "x");
  sample_pkb.InsertUses("main", "y");
  sample_pkb.InsertUses("main", "count");
  sample_pkb.InsertUses("printResults", "flag");
  sample_pkb.InsertUses("printResults", "cenX");
  sample_pkb.InsertUses("printResults", "cenY");
  sample_pkb.InsertUses("printResults", "normSq");
  sample_pkb.InsertUses("computeCentroid", "x");
  sample_pkb.InsertUses("computeCentroid", "y");
  sample_pkb.InsertUses("computeCentroid", "count");
  sample_pkb.InsertUses("computeCentroid", "cenX");
  sample_pkb.InsertUses("computeCentroid", "cenY");

  sample_pkb.InsertModifies(1, "flag");
  sample_pkb.InsertModifies(2, "x");
  sample_pkb.InsertModifies(2, "y");
  sample_pkb.InsertModifies(2, "count");
  sample_pkb.InsertModifies(2, "cenX");
  sample_pkb.InsertModifies(2, "cenY");
  sample_pkb.InsertModifies(2, "flag");
  sample_pkb.InsertModifies(2, "normSq");
  sample_pkb.InsertModifies(4, "x");
  sample_pkb.InsertModifies(5, "y");
  sample_pkb.InsertModifies(10, "count");
  sample_pkb.InsertModifies(11, "cenX");
  sample_pkb.InsertModifies(12, "cenY");
  sample_pkb.InsertModifies(13, "x");
  sample_pkb.InsertModifies(13, "y");
  sample_pkb.InsertModifies(14, "count");
  sample_pkb.InsertModifies(14, "cenX");
  sample_pkb.InsertModifies(14, "cenY");
  sample_pkb.InsertModifies(14, "x");
  sample_pkb.InsertModifies(14, "y");
  sample_pkb.InsertModifies(15, "count");
  sample_pkb.InsertModifies(16, "cenX");
  sample_pkb.InsertModifies(17, "cenY");
  sample_pkb.InsertModifies(18, "x");
  sample_pkb.InsertModifies(18, "y");
  sample_pkb.InsertModifies(19, "flag");
  sample_pkb.InsertModifies(19, "cenX");
  sample_pkb.InsertModifies(19, "cenY");
  sample_pkb.InsertModifies(20, "flag");
  sample_pkb.InsertModifies(21, "cenX");
  sample_pkb.InsertModifies(22, "cenY");
  sample_pkb.InsertModifies(23, "normSq");

  sample_pkb.InsertModifies("main", "count");
  sample_pkb.InsertModifies("main", "cenX");
  sample_pkb.InsertModifies("main", "cenY");
  sample_pkb.InsertModifies("main", "x");
  sample_pkb.InsertModifies("main", "y");
  sample_pkb.InsertModifies("main", "flag");
  sample_pkb.InsertModifies("main", "normSq");
  sample_pkb.InsertModifies("readPoint", "x");
  sample_pkb.InsertModifies("readPoint", "y");
  sample_pkb.InsertModifies("computeCentroid", "count");
  sample_pkb.InsertModifies("computeCentroid", "cenX");
  sample_pkb.InsertModifies("computeCentroid", "cenY");
  sample_pkb.InsertModifies("computeCentroid", "x");
  sample_pkb.InsertModifies("computeCentroid", "y");
  sample_pkb.InsertModifies("computeCentroid", "flag");
  sample_pkb.InsertModifies("computeCentroid", "normSq");

  sample_pkb.InsertCalls("main", "computeCentroid");
  sample_pkb.InsertCalls("main", "printResults");
  sample_pkb.InsertCalls("computeCentroid", "readPoint");
  sample_pkb.InsertCallsT("main", "computeCentroid");
  sample_pkb.InsertCallsT("main", "printResults");
  sample_pkb.InsertCallsT("computeCentroid", "readPoint");
  sample_pkb.InsertCallsT("main", "readPoint");

  sample_pkb.InsertNext(1, 2);
  sample_pkb.InsertNextT(1, 2);
  sample_pkb.InsertNextT(1, 3);
  sample_pkb.InsertNext(2, 3);
  sample_pkb.InsertNextT(2, 3);
  sample_pkb.InsertNext(4, 5);
  sample_pkb.InsertNextT(4, 5);
  sample_pkb.InsertNext(6, 7);
  sample_pkb.InsertNextT(6, 7);
  sample_pkb.InsertNextT(6, 8);
  sample_pkb.InsertNextT(6, 9);
  sample_pkb.InsertNext(7, 8);
  sample_pkb.InsertNextT(7, 8);
  sample_pkb.InsertNextT(7, 9);
  sample_pkb.InsertNext(8, 9);
  sample_pkb.InsertNextT(8, 9);
  sample_pkb.InsertNext(10, 11);
  sample_pkb.InsertNextT(10, 11);
  sample_pkb.InsertNextT(10, 12);
  sample_pkb.InsertNextT(10, 13);
  sample_pkb.InsertNextT(10, 14);
  sample_pkb.InsertNextT(10, 15);
  sample_pkb.InsertNextT(10, 16);
  sample_pkb.InsertNextT(10, 17);
  sample_pkb.InsertNextT(10, 18);
  sample_pkb.InsertNextT(10, 19);
  sample_pkb.InsertNextT(10, 20);
  sample_pkb.InsertNextT(10, 21);
  sample_pkb.InsertNextT(10, 22);
  sample_pkb.InsertNextT(10, 23);
  sample_pkb.InsertNext(11, 12);
  sample_pkb.InsertNextT(11, 12);
  sample_pkb.InsertNextT(11, 13);
  sample_pkb.InsertNextT(11, 14);
  sample_pkb.InsertNextT(11, 15);
  sample_pkb.InsertNextT(11, 16);
  sample_pkb.InsertNextT(11, 17);
  sample_pkb.InsertNextT(11, 18);
  sample_pkb.InsertNextT(11, 19);
  sample_pkb.InsertNextT(11, 20);
  sample_pkb.InsertNextT(11, 21);
  sample_pkb.InsertNextT(11, 22);
  sample_pkb.InsertNextT(11, 23);
  sample_pkb.InsertNext(12, 13);
  sample_pkb.InsertNextT(12, 13);
  sample_pkb.InsertNextT(12, 14);
  sample_pkb.InsertNextT(12, 15);
  sample_pkb.InsertNextT(12, 16);
  sample_pkb.InsertNextT(12, 17);
  sample_pkb.InsertNextT(12, 18);
  sample_pkb.InsertNextT(12, 19);
  sample_pkb.InsertNextT(12, 20);
  sample_pkb.InsertNextT(12, 21);
  sample_pkb.InsertNextT(12, 22);
  sample_pkb.InsertNextT(12, 23);
  sample_pkb.InsertNext(13, 14);
  sample_pkb.InsertNextT(13, 14);
  sample_pkb.InsertNextT(13, 15);
  sample_pkb.InsertNextT(13, 16);
  sample_pkb.InsertNextT(13, 17);
  sample_pkb.InsertNextT(13, 18);
  sample_pkb.InsertNextT(13, 19);
  sample_pkb.InsertNextT(13, 20);
  sample_pkb.InsertNextT(13, 21);
  sample_pkb.InsertNextT(13, 22);
  sample_pkb.InsertNextT(13, 23);
  sample_pkb.InsertNext(14, 15);
  sample_pkb.InsertNextT(14, 15);
  sample_pkb.InsertNextT(14, 16);
  sample_pkb.InsertNextT(14, 17);
  sample_pkb.InsertNextT(14, 18);
  sample_pkb.InsertNextT(14, 14);
  sample_pkb.InsertNext(14, 19);
  sample_pkb.InsertNextT(14, 19);
  sample_pkb.InsertNextT(14, 20);
  sample_pkb.InsertNextT(14, 21);
  sample_pkb.InsertNextT(14, 22);
  sample_pkb.InsertNextT(14, 23);
  sample_pkb.InsertNext(15, 16);
  sample_pkb.InsertNextT(15, 16);
  sample_pkb.InsertNextT(15, 17);
  sample_pkb.InsertNextT(15, 18);
  sample_pkb.InsertNextT(15, 14);
  sample_pkb.InsertNextT(15, 15);
  sample_pkb.InsertNextT(15, 19);
  sample_pkb.InsertNextT(15, 20);
  sample_pkb.InsertNextT(15, 21);
  sample_pkb.InsertNextT(15, 22);
  sample_pkb.InsertNextT(15, 23);
  sample_pkb.InsertNext(16, 17);
  sample_pkb.InsertNextT(16, 17);
  sample_pkb.InsertNextT(16, 18);
  sample_pkb.InsertNextT(16, 14);
  sample_pkb.InsertNextT(16, 15);
  sample_pkb.InsertNextT(16, 16);
  sample_pkb.InsertNextT(16, 19);
  sample_pkb.InsertNextT(16, 20);
  sample_pkb.InsertNextT(16, 21);
  sample_pkb.InsertNextT(16, 22);
  sample_pkb.InsertNextT(16, 23);
  sample_pkb.InsertNext(17, 18);
  sample_pkb.InsertNextT(17, 18);
  sample_pkb.InsertNextT(17, 14);
  sample_pkb.InsertNextT(17, 15);
  sample_pkb.InsertNextT(17, 16);
  sample_pkb.InsertNextT(17, 17);
  sample_pkb.InsertNextT(17, 19);
  sample_pkb.InsertNextT(17, 20);
  sample_pkb.InsertNextT(17, 21);
  sample_pkb.InsertNextT(17, 22);
  sample_pkb.InsertNextT(17, 23);
  sample_pkb.InsertNext(18, 14);
  sample_pkb.InsertNextT(18, 14);
  sample_pkb.InsertNextT(18, 15);
  sample_pkb.InsertNextT(18, 16);
  sample_pkb.InsertNextT(18, 17);
  sample_pkb.InsertNextT(18, 18);
  sample_pkb.InsertNextT(18, 19);
  sample_pkb.InsertNextT(18, 20);
  sample_pkb.InsertNextT(18, 21);
  sample_pkb.InsertNextT(18, 22);
  sample_pkb.InsertNextT(18, 23);
  sample_pkb.InsertNext(19, 20);
  sample_pkb.InsertNextT(19, 20);
  sample_pkb.InsertNext(19, 21);
  sample_pkb.InsertNextT(19, 21);
  sample_pkb.InsertNextT(19, 22);
  sample_pkb.InsertNextT(19, 23);
  sample_pkb.InsertNext(21, 22);
  sample_pkb.InsertNextT(21, 22);
  sample_pkb.InsertNextT(21, 23);
  sample_pkb.InsertNext(20, 23);
  sample_pkb.InsertNextT(20, 23);
  sample_pkb.InsertNext(22, 23);
  sample_pkb.InsertNextT(22, 23);

  sample_pkb.InsertAffects(10, 15);
  sample_pkb.InsertAffectsT(10, 15);
  sample_pkb.InsertAffects(10, 21);
  sample_pkb.InsertAffectsT(10, 21);
  sample_pkb.InsertAffects(10, 22);
  sample_pkb.InsertAffectsT(10, 22);
  sample_pkb.InsertAffectsT(10, 23);
  sample_pkb.InsertAffects(11, 16);
  sample_pkb.InsertAffectsT(11, 16);
  sample_pkb.InsertAffects(11, 21);
  sample_pkb.InsertAffectsT(11, 21);
  sample_pkb.InsertAffects(11, 23);
  sample_pkb.InsertAffectsT(11, 23);
  sample_pkb.InsertAffects(12, 17);
  sample_pkb.InsertAffectsT(12, 17);
  sample_pkb.InsertAffects(12, 22);
  sample_pkb.InsertAffectsT(12, 22);
  sample_pkb.InsertAffects(12, 23);
  sample_pkb.InsertAffectsT(12, 23);
  sample_pkb.InsertAffects(15, 15);
  sample_pkb.InsertAffectsT(15, 15);
  sample_pkb.InsertAffects(16, 16);
  sample_pkb.InsertAffectsT(16, 16);
  sample_pkb.InsertAffects(17, 17);
  sample_pkb.InsertAffectsT(17, 17);
  sample_pkb.InsertAffects(15, 21);
  sample_pkb.InsertAffectsT(15, 21);
  sample_pkb.InsertAffects(15, 22);
  sample_pkb.InsertAffectsT(15, 22);
  sample_pkb.InsertAffectsT(15, 23);
  sample_pkb.InsertAffects(16, 21);
  sample_pkb.InsertAffectsT(16, 21);
  sample_pkb.InsertAffects(17, 22);
  sample_pkb.InsertAffectsT(17, 22);
  sample_pkb.InsertAffects(16, 23);
  sample_pkb.InsertAffectsT(16, 23);
  sample_pkb.InsertAffects(17, 23);
  sample_pkb.InsertAffectsT(17, 23);
  sample_pkb.InsertAffects(21, 23);
  sample_pkb.InsertAffectsT(21, 23);
  sample_pkb.InsertAffects(22, 23);
  sample_pkb.InsertAffectsT(22, 23);

  // Relationships that are same as Next and NextT
  sample_pkb.InsertNextBip(1, 2);
  sample_pkb.InsertNextBipT(1, 2);
  sample_pkb.InsertNextBipT(1, 3);
  sample_pkb.InsertNextBip(2, 3);
  sample_pkb.InsertNextBipT(2, 3);
  sample_pkb.InsertNextBip(4, 5);
  sample_pkb.InsertNextBipT(4, 5);
  sample_pkb.InsertNextBip(6, 7);
  sample_pkb.InsertNextBipT(6, 7);
  sample_pkb.InsertNextBipT(6, 8);
  sample_pkb.InsertNextBipT(6, 9);
  sample_pkb.InsertNextBip(7, 8);
  sample_pkb.InsertNextBipT(7, 8);
  sample_pkb.InsertNextBipT(7, 9);
  sample_pkb.InsertNextBip(8, 9);
  sample_pkb.InsertNextBipT(8, 9);
  sample_pkb.InsertNextBip(10, 11);
  sample_pkb.InsertNextBipT(10, 11);
  sample_pkb.InsertNextBipT(10, 12);
  sample_pkb.InsertNextBipT(10, 13);
  sample_pkb.InsertNextBipT(10, 14);
  sample_pkb.InsertNextBipT(10, 15);
  sample_pkb.InsertNextBipT(10, 16);
  sample_pkb.InsertNextBipT(10, 17);
  sample_pkb.InsertNextBipT(10, 18);
  sample_pkb.InsertNextBipT(10, 19);
  sample_pkb.InsertNextBipT(10, 20);
  sample_pkb.InsertNextBipT(10, 21);
  sample_pkb.InsertNextBipT(10, 22);
  sample_pkb.InsertNextBipT(10, 23);
  sample_pkb.InsertNextBip(11, 12);
  sample_pkb.InsertNextBipT(11, 12);
  sample_pkb.InsertNextBipT(11, 13);
  sample_pkb.InsertNextBipT(11, 14);
  sample_pkb.InsertNextBipT(11, 15);
  sample_pkb.InsertNextBipT(11, 16);
  sample_pkb.InsertNextBipT(11, 17);
  sample_pkb.InsertNextBipT(11, 18);
  sample_pkb.InsertNextBipT(11, 19);
  sample_pkb.InsertNextBipT(11, 20);
  sample_pkb.InsertNextBipT(11, 21);
  sample_pkb.InsertNextBipT(11, 22);
  sample_pkb.InsertNextBipT(11, 23);
  sample_pkb.InsertNextBip(12, 13);
  sample_pkb.InsertNextBipT(12, 13);
  sample_pkb.InsertNextBipT(12, 14);
  sample_pkb.InsertNextBipT(12, 15);
  sample_pkb.InsertNextBipT(12, 16);
  sample_pkb.InsertNextBipT(12, 17);
  sample_pkb.InsertNextBipT(12, 18);
  sample_pkb.InsertNextBipT(12, 19);
  sample_pkb.InsertNextBipT(12, 20);
  sample_pkb.InsertNextBipT(12, 21);
  sample_pkb.InsertNextBipT(12, 22);
  sample_pkb.InsertNextBipT(12, 23);
  sample_pkb.InsertNextBip(13, 14);
  sample_pkb.InsertNextBipT(13, 14);
  sample_pkb.InsertNextBipT(13, 15);
  sample_pkb.InsertNextBipT(13, 16);
  sample_pkb.InsertNextBipT(13, 17);
  sample_pkb.InsertNextBipT(13, 18);
  sample_pkb.InsertNextBipT(13, 19);
  sample_pkb.InsertNextBipT(13, 20);
  sample_pkb.InsertNextBipT(13, 21);
  sample_pkb.InsertNextBipT(13, 22);
  sample_pkb.InsertNextBipT(13, 23);
  sample_pkb.InsertNextBip(14, 15);
  sample_pkb.InsertNextBipT(14, 15);
  sample_pkb.InsertNextBipT(14, 16);
  sample_pkb.InsertNextBipT(14, 17);
  sample_pkb.InsertNextBipT(14, 18);
  sample_pkb.InsertNextBipT(14, 14);
  sample_pkb.InsertNextBip(14, 19);
  sample_pkb.InsertNextBipT(14, 19);
  sample_pkb.InsertNextBipT(14, 20);
  sample_pkb.InsertNextBipT(14, 21);
  sample_pkb.InsertNextBipT(14, 22);
  sample_pkb.InsertNextBipT(14, 23);
  sample_pkb.InsertNextBip(15, 16);
  sample_pkb.InsertNextBipT(15, 16);
  sample_pkb.InsertNextBipT(15, 17);
  sample_pkb.InsertNextBipT(15, 18);
  sample_pkb.InsertNextBipT(15, 14);
  sample_pkb.InsertNextBipT(15, 15);
  sample_pkb.InsertNextBipT(15, 19);
  sample_pkb.InsertNextBipT(15, 20);
  sample_pkb.InsertNextBipT(15, 21);
  sample_pkb.InsertNextBipT(15, 22);
  sample_pkb.InsertNextBipT(15, 23);
  sample_pkb.InsertNextBip(16, 17);
  sample_pkb.InsertNextBipT(16, 17);
  sample_pkb.InsertNextBipT(16, 18);
  sample_pkb.InsertNextBipT(16, 14);
  sample_pkb.InsertNextBipT(16, 15);
  sample_pkb.InsertNextBipT(16, 16);
  sample_pkb.InsertNextBipT(16, 19);
  sample_pkb.InsertNextBipT(16, 20);
  sample_pkb.InsertNextBipT(16, 21);
  sample_pkb.InsertNextBipT(16, 22);
  sample_pkb.InsertNextBipT(16, 23);
  sample_pkb.InsertNextBip(17, 18);
  sample_pkb.InsertNextBipT(17, 18);
  sample_pkb.InsertNextBipT(17, 14);
  sample_pkb.InsertNextBipT(17, 15);
  sample_pkb.InsertNextBipT(17, 16);
  sample_pkb.InsertNextBipT(17, 17);
  sample_pkb.InsertNextBipT(17, 19);
  sample_pkb.InsertNextBipT(17, 20);
  sample_pkb.InsertNextBipT(17, 21);
  sample_pkb.InsertNextBipT(17, 22);
  sample_pkb.InsertNextBipT(17, 23);
  sample_pkb.InsertNextBip(18, 14);
  sample_pkb.InsertNextBipT(18, 14);
  sample_pkb.InsertNextBipT(18, 15);
  sample_pkb.InsertNextBipT(18, 16);
  sample_pkb.InsertNextBipT(18, 17);
  sample_pkb.InsertNextBipT(18, 18);
  sample_pkb.InsertNextBipT(18, 19);
  sample_pkb.InsertNextBipT(18, 20);
  sample_pkb.InsertNextBipT(18, 21);
  sample_pkb.InsertNextBipT(18, 22);
  sample_pkb.InsertNextBipT(18, 23);
  sample_pkb.InsertNextBip(19, 20);
  sample_pkb.InsertNextBipT(19, 20);
  sample_pkb.InsertNextBip(19, 21);
  sample_pkb.InsertNextBipT(19, 21);
  sample_pkb.InsertNextBipT(19, 22);
  sample_pkb.InsertNextBipT(19, 23);
  sample_pkb.InsertNextBip(21, 22);
  sample_pkb.InsertNextBipT(21, 22);
  sample_pkb.InsertNextBipT(21, 23);
  sample_pkb.InsertNextBip(20, 23);
  sample_pkb.InsertNextBipT(20, 23);
  sample_pkb.InsertNextBip(22, 23);
  sample_pkb.InsertNextBipT(22, 23);

  //Relationships unique to NextBip and NextBipT
  for (int i = 4; i < 23; i++) {
    sample_pkb.InsertNextBipT(1, i);
    sample_pkb.InsertNextBipT(2, i);
  }
  sample_pkb.InsertNextBip(2, 10);
  sample_pkb.InsertNextBip(3, 6);
  sample_pkb.InsertNextBipT(3, 6);
  sample_pkb.InsertNextBipT(3, 7);
  sample_pkb.InsertNextBipT(3, 8);
  sample_pkb.InsertNextBipT(3, 9);
  sample_pkb.InsertNextBipT(4, 4);
  sample_pkb.InsertNextBipT(4, 6);
  sample_pkb.InsertNextBipT(4, 7);
  sample_pkb.InsertNextBipT(4, 8);
  sample_pkb.InsertNextBipT(4, 9);
  for (int i = 14; i <= 23; i++) {
    sample_pkb.InsertNextBipT(4, i);
    sample_pkb.InsertNextBipT(5, i);
  }
  sample_pkb.InsertNextBip(5, 14);
  sample_pkb.InsertNextBipT(5, 4);
  sample_pkb.InsertNextBipT(5, 5);
  sample_pkb.InsertNextBipT(5, 6);
  sample_pkb.InsertNextBipT(5, 7);
  sample_pkb.InsertNextBipT(5, 8);
  sample_pkb.InsertNextBipT(5, 9);
  sample_pkb.InsertNextBip(13, 4);
  sample_pkb.InsertNextBip(18, 4);
  for (int i = 10; i <= 23; i++) {
    sample_pkb.InsertNextBipT(i, 6);
    sample_pkb.InsertNextBipT(i, 7);
    sample_pkb.InsertNextBipT(i, 8);
    sample_pkb.InsertNextBipT(i, 9);
  }
  for (int i = 13; i <= 18; i++) {
    sample_pkb.InsertNextBipT(i, 4);
    sample_pkb.InsertNextBipT(i, 5);
  }

  // Relationships same as Affects/T
  sample_pkb.InsertAffectsBip(10, 15);
  sample_pkb.InsertAffectsBipT(10, 15);
  sample_pkb.InsertAffectsBip(10, 21);
  sample_pkb.InsertAffectsBipT(10, 21);
  sample_pkb.InsertAffectsBip(10, 22);
  sample_pkb.InsertAffectsBipT(10, 22);
  sample_pkb.InsertAffectsBipT(10, 23);
  sample_pkb.InsertAffectsBip(11, 16);
  sample_pkb.InsertAffectsBipT(11, 16);
  sample_pkb.InsertAffectsBip(11, 21);
  sample_pkb.InsertAffectsBipT(11, 21);
  sample_pkb.InsertAffectsBip(11, 23);
  sample_pkb.InsertAffectsBipT(11, 23);
  sample_pkb.InsertAffectsBip(12, 17);
  sample_pkb.InsertAffectsBipT(12, 17);
  sample_pkb.InsertAffectsBip(12, 22);
  sample_pkb.InsertAffectsBipT(12, 22);
  sample_pkb.InsertAffectsBip(12, 23);
  sample_pkb.InsertAffectsBipT(12, 23);
  sample_pkb.InsertAffectsBip(15, 15);
  sample_pkb.InsertAffectsBipT(15, 15);
  sample_pkb.InsertAffectsBip(16, 16);
  sample_pkb.InsertAffectsBipT(16, 16);
  sample_pkb.InsertAffectsBip(17, 17);
  sample_pkb.InsertAffectsBipT(17, 17);
  sample_pkb.InsertAffectsBip(15, 21);
  sample_pkb.InsertAffectsBipT(15, 21);
  sample_pkb.InsertAffectsBip(15, 22);
  sample_pkb.InsertAffectsBipT(15, 22);
  sample_pkb.InsertAffectsBipT(15, 23);
  sample_pkb.InsertAffectsBip(16, 21);
  sample_pkb.InsertAffectsBipT(16, 21);
  sample_pkb.InsertAffectsBip(17, 22);
  sample_pkb.InsertAffectsBipT(17, 22);
  sample_pkb.InsertAffectsBip(16, 23);
  sample_pkb.InsertAffectsBipT(16, 23);
  sample_pkb.InsertAffectsBip(17, 23);
  sample_pkb.InsertAffectsBipT(17, 23);
  sample_pkb.InsertAffectsBip(21, 23);
  sample_pkb.InsertAffectsBipT(21, 23);
  sample_pkb.InsertAffectsBip(22, 23);
  sample_pkb.InsertAffectsBipT(22, 23);

  return sample_pkb;
}

/*
 *    procedure main {
 * 01   while (x > 0) {
 * 02       while (y > 0) {
 * 03           y = y - 1;
 * 04           while (z > 0) {
 * 05               z = z - 1;
 *              }
 * 06           if (y == z) then {
 * 07               print y;
 *              } else {
 * 08               print z;
 *              }
 *          }
 *       }
 * 09   print x;
 *    }
 */
PKB BuildNestedProgram() {
  PKB sample_pkb = PKB();

  Token minus("-", TokenType::ExpressionOp);
  Token x("x", TokenType::VariableName);
  Token y("y", TokenType::VariableName);
  Token z("z", TokenType::VariableName);
  Token one("1", TokenType::ConstantValue);

  TokenList tokens3;
  TokenList tokens5;

  tokens3.Push(y).Push(minus).Push(one);
  tokens5.Push(z).Push(minus).Push(one);

  for (int i = 1; i <= 9; i++) {
    sample_pkb.InsertStatement(i);
  }
  sample_pkb.InsertProcedure("main", 1, 9);
  sample_pkb.InsertWhile(1, {"x"});
  sample_pkb.InsertWhile(2, {"y"});
  sample_pkb.InsertWhile(4, {"z"});
  sample_pkb.InsertIf(6, {"y", "z"});
  sample_pkb.InsertVariable("x");
  sample_pkb.InsertVariable("y");
  sample_pkb.InsertVariable("z");
  sample_pkb.InsertAssignment(3, {"y"}, tokens3);
  sample_pkb.InsertAssignment(5, {"z"}, tokens5);
  sample_pkb.InsertConstant(1);
  sample_pkb.InsertConstant(0);
  sample_pkb.InsertPrint(7, "y");
  sample_pkb.InsertPrint(8, "z");
  sample_pkb.InsertPrint(9, "x");

  sample_pkb.InsertFollows(3, 4);
  sample_pkb.InsertFollowsT(3, 4);
  sample_pkb.InsertFollows(4, 6);
  sample_pkb.InsertFollowsT(4, 6);
  sample_pkb.InsertFollowsT(3, 6);
  sample_pkb.InsertFollows(1, 9);
  sample_pkb.InsertFollowsT(1, 9);

  sample_pkb.InsertParent(1, 2);
  sample_pkb.InsertParentT(1, 2);
  sample_pkb.InsertParent(2, 3);
  sample_pkb.InsertParentT(2, 3);
  sample_pkb.InsertParentT(1, 3);
  sample_pkb.InsertParent(2, 4);
  sample_pkb.InsertParentT(2, 4);
  sample_pkb.InsertParentT(1, 4);
  sample_pkb.InsertParent(4, 5);
  sample_pkb.InsertParentT(4, 5);
  sample_pkb.InsertParentT(2, 5);
  sample_pkb.InsertParentT(1, 5);
  sample_pkb.InsertParent(2, 6);
  sample_pkb.InsertParentT(2, 6);
  sample_pkb.InsertParentT(1, 6);
  sample_pkb.InsertParent(6, 7);
  sample_pkb.InsertParentT(6, 7);
  sample_pkb.InsertParentT(2, 7);
  sample_pkb.InsertParentT(1, 7);
  sample_pkb.InsertParent(6, 8);
  sample_pkb.InsertParentT(6, 8);
  sample_pkb.InsertParentT(2, 8);
  sample_pkb.InsertParentT(1, 8);

  sample_pkb.InsertUses(1, "x");
  sample_pkb.InsertUses(1, "y");
  sample_pkb.InsertUses(1, "z");
  sample_pkb.InsertUses(2, "y");
  sample_pkb.InsertUses(2, "z");
  sample_pkb.InsertUses(3, "y");
  sample_pkb.InsertUses(4, "z");
  sample_pkb.InsertUses(5, "z");
  sample_pkb.InsertUses(6, "y");
  sample_pkb.InsertUses(6, "z");
  sample_pkb.InsertUses(7, "y");
  sample_pkb.InsertUses(8, "z");
  sample_pkb.InsertUses(9, "x");

  sample_pkb.InsertModifies(1, "y");
  sample_pkb.InsertModifies(1, "z");
  sample_pkb.InsertModifies(2, "y");
  sample_pkb.InsertModifies(2, "z");
  sample_pkb.InsertModifies(3, "y");
  sample_pkb.InsertModifies(4, "z");
  sample_pkb.InsertModifies(5, "z");

  return sample_pkb;
}